### ISSUE TITLE
Unable to run script

### ISSUE THREAD

**Issue by vitorguidi** [ufcg-lsd/autoscaling-analyser#32]
I am following the README in order to install, and I attempted this command

'''
> install.packages("dplyr", "testthat", "yaml", "yardstick", "R.utils", "purrr", "reticulate")
Warning in install.packages("dplyr", "testthat", "yaml", "yardstick", "R.utils",  :
  'lib = "testthat"' is not writable
Would you like to use a personal library instead? (yes/No/cancel) yes
Error in download.packages(pkgs, destdir = tmpd, available = available,  : 
  'destdir' is not a directory
In addition: Warning message:
package ‘dplyr’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
'''

It fails, as i am unable to install dependencies.

Is there a restriction on OS/R version to use this script?

**Comment by vitorguidi** [comment]
Apparently the default repository was not working. I brute forced all 7 libs through this repo and it worked :shrug: 

install.packages('dplyr', repos = 'https://cloud.r-project.org')
install.packages('dplyr', repos = 'https://cloud.r-project.org')
install.packages('yaml', repos = 'https://cloud.r-project.org')
install.packages('yardstick', repos = 'https://cloud.r-project.org')
install.packages('R.utils', repos = 'https://cloud.r-project.org')
install.packages('purrr', repos = 'https://cloud.r-project.org')
install.packages('reticulate', repos = 'https://cloud.r-project.org')

**Comment by samarasss** [comment]
Issue Resolved
